docs: update README.md

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,3 +3,16 @@
 . "$(dirname "$0")/_/husky.sh"
 
 yarn pre:commit
+
+
+### PROTECTED BRANCHES
+
+# shellcheck disable=SC2006
+BRANCH=`git rev-parse --abbrev-ref HEAD`
+PROTECTED_BRANCHES="^(master|develop)"
+
+# shellcheck disable=SC2039
+if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
+then
+  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR." && exit 1
+fi
